# Yazi File Manager Configuration
# https://yazi-rs.github.io/docs/configuration/yazi

[mgr]
linemode = "size"

[opener]
edit = [
  { run = 'nvim "$@"', desc = "Edit with Neovim", block = true, for = "unix" },
]
play = [{ run = 'mpv --force-window "$@"', orphan = true, for = "unix" }]
